<?php

/**
 * Users.
 *
 * @autogenerated by Phalcon Developer Tools
 * @date 2016-09-25, 08:29:01
 */
class Users extends \Phalcon\Mvc\Model
{
    /**
     * @var string
     * @Primary
     * @Column(type="string", length=10, nullable=false)
     */
    public $name;

    /**
     * @var int
     * @Column(type="integer", length=40, nullable=false)
     */
    public $money;

    /**
     * @var int
     * @Column(type="integer", length=40, nullable=false)
     */
    public $energy;

    /**
     * @var string
     * @Column(type="string", nullable=false)
     */
    public $created_at;

    /**
     * @var string
     * @Column(type="string", nullable=false)
     */
    public $updated_at;

    /**
     * Allows to query a set of records that match the specified conditions.
     *
     * @param mixed $parameters
     *
     * @return Users[]
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions.
     *
     * @param mixed $parameters
     *
     * @return Users
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

    public function test()
    {
        return 1;
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'users';
    }
}
